# Generated by Django 3.0.4 on 2020-03-28 11:13

from django.db import migrations

import logging

logger = logging.getLogger(__name__)

def add_group(apps, schema_editor):
    """ This function use to add the initial group for our app """

    Group = apps.get_model('auth', 'Group')

    # Admin group
    Group.objects.create(name='admin_user')
    logger.info('Admin group created')

    # standard
    Group.objects.create(name='standard_user')
    logger.info('standard_user Group created')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_group),
    ]
