# Generated by Django 3.0.4 on 2020-03-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200328_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='thumbnail_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
